Project/Project/Models/Shipment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int Route_ID { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<double> Base_Price { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> Company_ID { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}

Project/Project/Controllers/ShipmentController.cs
using Project.Models;
using Project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class ShipmentController : Controller
    {
        // GET: Shipment
        ShipmentContext shipmentContext;
        CompanyContext companyContext;

        public ShipmentController()
        {
            this.shipmentContext = new ShipmentContext();
            this.companyContext = new CompanyContext();
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add_Route()
        {
            //Session["Action"] = "Add_Route";
            //Session["Controller"]="Orders";
            return View();
        }
        [HttpPost]
        public ActionResult Add_Route(Shipment ship)
        {
            if (Session["user_store"] != null)
            {
                if (ModelState.IsValid)
                {
                    var comp_id = companyContext.Comp_by_ID(Convert.ToInt32(Session["user_store"]));

                    var ship_data = (from shipmentData in shipmentContext.Get().ToList() where ship.Source.ToLower().Trim() == shipmentData.Source.ToLower().Trim() && ship.Destination.ToLower().Trim() == shipmentData.Destination.ToLower().Trim() && comp_id == shipmentData.Company_ID select shipmentData).ToList();

                    if (ship_data.Count() > 0)
                    {
                        ViewBag.RouteError = "Already Having this Route !!";
                        return View();
                    }
                    else
                    {
                        ship.Company_ID = comp_id;
                        shipmentContext.add(ship);
                    }
                }
                return View();
            }
            return RedirectToAction("Login", "User");
        }

        public ActionResult Display_Route()
        {
            if (Session["user_store"] != null)
            {
                var order = (List<string>)TempData["order"];
                var routes = (shipmentContext.Get()).Where(value => value.Source == order[0] && value.Destination == order[1]).ToList();
                TempData.Keep("order");
                if (routes.Count() > 0)
                {
                    return View(routes);
                }
                else
                {
                    ViewBag.route_msg = "Currently WE Don't Have Any Service in this Route  So we Can't Take your Order";
                }
                return View();
            }
            return RedirectToAction("Login", "User");
        }
        //    [HttpPost]
        public ActionResult Confirm(int? id)
        {

            int id_store = (int)id;
            TempData["ship"] = shipmentContext.Get_ID_Details(id_store);
            return RedirectToAction("ConfirmOrder", "Orders");
        }

        //  [HttpPost]
        public ActionResult Show_Company(int? id)
        {
            TempData["comp_store_id"] = (int)id;
            return RedirectToAction("DisplayCompany", "Company");
        }
    
}
}

Project/Project/Views/Shipment/Add_Route.cshtml
@model Project.Models.Shipment

@{
    ViewBag.Title = "Add_Route";
}
<body class="btn-route" style="background-image: url('/Images/logistic_2.jpg'); background-size: cover;">


    @using (Html.BeginForm("Add_Route", "Shipment", FormMethod.Post))
    {
        @Html.AntiForgeryToken()



        <div class="login-page-1-2">


            @*<form name="ship" class="route-form-4" id="form" action="~/Shipment/Add_Route" method="post">*@

            <div>
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @if (ViewBag.RouteError != null)
                {
                    <div style="border: 1px solid red;background-color:ghostwhite;text-align:center;margin-top:10px;">
                        <h1>  @ViewBag.RouteError</h1>
                    </div>
                }
                <div style="margin-top:100px;background-color:gainsboro;padding-top:20px;padding-bottom:20px;border-block-color:aquamarine;border-radius:8px;">
                    <div class="input-control_1" style="margin-left:150px">
                        <table width="90%" id="table_1">

                            <tr>
                                <td style="width:250px"><div class="div_1"><input type="text" class="login_input_1" id="Source" placeholder="Source" required="required" name="Source"></div></td>
                                @Html.ValidationMessageFor(model => model.Source, "", new { @class = "text-danger" })
                                <td style="width:250px"><div class="div_1"><input type="text" class="login_input_1" id="Destination" placeholder="Destination" required="required" name="Destination"></div></td>
                                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
                                <td style="width:250px"><div class="div_1"><input type="number" class="login_input_1" id="Distance" placeholder="Distance" required="required" name="Distance" min="1" max="5000"></div></td>
                                @Html.ValidationMessageFor(model => model.Distance, "", new { @class = "text-danger" })
                                <td style="width:250px"><div class="div_1"><input type="number" class="login_input_1" id="BasePrice" placeholder="Base Price" required="required" name="Base_Price"></div></td>
                                @Html.ValidationMessageFor(model => model.Base_Price, "", new { @class = "text-danger" })
                            </tr>
                            <tr>
                                <td colspan="4" style="text-align:center"></td>
                            </tr>

                        </table>
                    </div>

                    <div class="btn_sub-1" style="margin-left:30% ;margin-right:30%">
                        @*      <button type="button" class="btn btn-success" onclick="addRow()" style="text-align:center;">Click to add row at the bottom of Table</button>*@
                        <button type="submit" value="Add_Route" class="btn btn-primary" style="text-align: center;margin-left:40px;margin-right:40px;">Submit</button>
                        @*    <button type="button" class="btn btn-danger" onclick="deleteRow()" style="text-align:center;margin-left:40px;">Click to delete row at the bottom of Table</button>*@
                    </div>
                </div>
            </div>
        </div>
    }
     
      <div style="height:200px;"></div>
    
</body>
<script>

    function addRow() {
        var table = document.getElementById("table_1");
        var rws = table.rows;
        var cols = table.rows[0].cells.length;
        var row = table.insertRow(rws.length);
        var cell = row.insertCell(0);
        cell.innerHTML = '<div class="div_1"><input type="text" class="login_input_1" id="Source" placeholder="Source" required="required" name="Source"></div>';
        var cell1 = row.insertCell(1);
        cell1.innerHTML = '<div class="div_1"><input type="text" class="login_input_1" id="Destination" placeholder="Destination" required="required" name="Destination">';
        var cell2 = row.insertCell(2);
        cell2.innerHTML = '<div class="div_1"><input type="text" class="login_input_1" id="Distance" placeholder="Distance" required="required" name="Distance" min="1" max="5000"></div>';
        var cell3 = row.insertCell(3);
        cell3.innerHTML = '<div><input type="text" class="login_input_1" id="BasePrice" placeholder="Base Price" required="required" name="Base_Price"></div>';
    }
    function deleteRow() {
        var table = document.getElementById("table_1");
        var rws = table.rows;
        if (rws.length > 1) { document.getElementById("table_1").deleteRow(rws); }
    }

    function storeData() {

    }

</script>
  

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/Shipment/Display_Route.cshtml
@model IEnumerable<Project.Models.Shipment>

<style>
    th {
        padding: 10px;
        font-size: medium;
        background-color: darksalmon;
        text-align: center;
    }
</style>

<body class="admin-div">

    <div class="bg-image h-100" style="background-color: #8ebcdb; margin-top:5%">
        @if (ViewBag.route_msg != null)
        {
            <div style="border: 1px solid red ;font-size:larger; height:50px">
                @ViewBag.route_msg
            </div>

            <p>
                @Html.ActionLink("Back to PlaceOrder", "PlaceOrder", "Orders")
            </p>
        }
        else
        {
            <h2 style="text-align:center;"><b>List Of Companies </b></h2>
            <table class="table table-bordered .thead-light" style="background-color:lightgray;text-align:center">
                <tr>
                    <th>
                        <b>  ROUTE ID</b>

                    </th>
                    <th>
                        <b>SOURCE</b>

                    </th>
                    <th>
                        <b>DESTINATION</b>

                    </th>
                    <th>
                        <b>BASE PRICE</b>

                    </th>
                    <th>
                        <b>DISTANCE</b>

                    </th>
                    <th>
                        <b>COMPANY NAME</b>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>

                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Route_ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Source)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Destination)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Base_Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Distance)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Company.Company_Name)
                        </td>
                        <td>
                            @Html.ActionLink("COMPANY DETAIL", "Show_Company", new { id = item.Company_ID })
                        </td>
                        <td>
                            @Html.ActionLink("Select", "Confirm", new { id = item.Route_ID }, new { @class = "btn btn-success" })
                        </td>
                    </tr>
                }

            </table>
        }
    </div>
     <div style="height:200px;"></div>
</body>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}