Project/Project/Controllers/AdminController.cs
using Project.Models;
using Project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        UserContext userContext;
        CompanyContext compContext;
        OrdersContext ordersContext;
       
        public AdminController()
        {
            userContext = new UserContext();
            compContext = new CompanyContext();
            ordersContext = new OrdersContext();
          
        }
        public ActionResult Request_List()
        {
            List<User> users = userContext.Get().ToList();
            List<Company> companies = compContext.Get().ToList();


            var Un_verify_Company = (from user in users
                                     join company in companies on user.Users_ID equals company.User_ids
                                     where user.user_status == "-1"
                                     select new
                                     {
                                         user = user,
                                         company = company,
                                     }).ToList().Distinct();

            List<Register_Company> register_Companies = new List<Register_Company>();

            foreach (var iterator in Un_verify_Company)
            {
                Register_Company register_Company = new Register_Company();
                register_Company.user = iterator.user;
                register_Company.company = iterator.company;
                register_Companies.Add(register_Company);
            }

            return View(register_Companies);
        }

        public ActionResult Approve(int id)
        {
            User user = userContext.Update(id);
            return RedirectToAction("Request_List");
        }

        public ActionResult Delete(int id)
        {

            compContext.Delete_UserID(id);
            userContext.Delete(id);
            return RedirectToAction("Request_List");
        }

        public ActionResult ShowOrders()
        {
            var data = ordersContext.Get();
            return View(data);
        }

        public ActionResult Companies()
        {
            var data = (from company in compContext.Get()
                        join user in userContext.Get() on company.User_ids equals
                       user.Users_ID
                        where user.user_status == "1"
                        select company).ToList();
            return View(data);
        }

        public ActionResult Users()
        {
            var data = userContext.Get();
            return View(data);
        }
        public ActionResult Disable(int userid)
        {

            return View();
        }

    }
}

Project/Project/Controllers/OrdersController.cs
using Project.Models;
using Project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
   
        // GET: Orders
        public class OrdersController : Controller
        {
            OrdersContext ordersContext;
            ShipmentContext shipmentContext;
            TrackingContext trackingContext;
            UserContext userContext;
            PaymentContext paymentContext;
            public OrdersController()
            {
                ordersContext = new OrdersContext();
                shipmentContext = new ShipmentContext();
                userContext = new UserContext();
                trackingContext = new TrackingContext();
                paymentContext = new PaymentContext();
            }
            public ActionResult Index()
            {
                return View();
            }

            public ActionResult PlaceOrder()
            {
                if (Session["user_store"] != null)
                {
                    var source = (from source_data in shipmentContext.Get().ToList() select source_data.Source).Distinct().ToList();
                    ViewBag.source_data = source;
                    var destination = (from source_data in shipmentContext.Get().ToList() select source_data.Destination).Distinct().ToList();
                    ViewBag.dest_data = destination;
                    return View();
                }
                else
                    return RedirectToAction("Login", "User");
            }
            [HttpPost]
            public ActionResult PlaceOrder(Order_Details order)
            {
                if (ModelState.IsValid)
                {
                    List<string> store = new List<string>();
                    store.Add(order.Order_Source);
                    store.Add(order.Order_Destination);
                    TempData["order"] = store;
                    TempData["order_data"] = order;
                    return RedirectToAction("Display_Route", "Shipment");
                }
                ViewBag.PlaceOrderError = "Please Enter Valid Address";
                return RedirectToAction("PlaceOrder");
                // return View(order);
            }

            public ActionResult ConfirmOrder()
            {
                if (Session["user_store"] != null)
                {
                    if (TempData["ship"] != null)
                    {
                        Shipment shipment = (Shipment)TempData["ship"];
                        TempData.Keep("ship");
                        Order_Details order = (Order_Details)TempData["order_data"];
                        TempData.Keep("order_data");
                        double price = (((int)order.Quantity) * ((double)(order.OrderWeight) * 0.05)) * ((int)order.Order_Valuation)*0.02 + (((double)(shipment.Base_Price)) * ((double)shipment.Distance)) * 0.5;
                        order.User_ids = Convert.ToInt32(Session["user_store"]);
                        order.Order_Time = DateTime.Now;
                        order.Total_Price = price;
                        order.Ship_ID = shipment.Route_ID;

                        ordersContext.add(order);

                        Payment payment = new Payment();
                        payment.Order_ID = order.Order_ID;
                        payment.Bill = (double)order.Total_Price;
                        payment.Pay_Status = false;
                        paymentContext.add(payment);
                        Session["order_d"] = order;
                        return RedirectToAction("Pay", new { pay_id = payment.Invoice_No });
                    }
                    return View();
                }
                return RedirectToAction("Login", "User");
            }
            public ActionResult Pay(int pay_id)
            {
                if (Session["user_store"] != null)
                {
                    Payment pay = paymentContext.Get_ID(pay_id);

                    //List<string> pay_type = new List<string> { "UPI", "Net Banking ", "Credit Card ", "Paytm", "PhonePay" };
                    // TempData["list"] = pay_type;
                    ViewBag.Pay = pay;
                    TempData["payment_invoice"] = pay.Invoice_No;
                    return View(pay);
                }
                return RedirectToAction("Login", "User");
            }
            [HttpPost]
            public ActionResult Pay(Payment payment)
            {
                // var order = (Order_Details)Session["order_d"];
                if (Session["user_store"] != null)
                {
                    ProjectEntities _context = new ProjectEntities();
                    //  var ord = _context.Order_Details.Find(order.Order_ID);
                    var pay_update = _context.Payments.Find((int)(TempData["payment_invoice"]));
                    TempData.Keep("payment_invoice");
                    pay_update.Pay_Status = true;
                    pay_update.Payment_time = DateTime.Now;
                    pay_update.Payment_Mode = "Credit Card";
                    _context.SaveChanges();
                    List<int> l2 = new List<int>();
                    l2.Add((int)pay_update.Order_ID);     // storing order id 
                    l2.Add((int)pay_update.Order_Details.Shipment.Company_ID);  // storing company id
                    TempData["track_data"] = l2;
                    return RedirectToAction("Add", "Tracking");
                }
                return RedirectToAction("Login", "User");
            }


            public ActionResult ShowPlacedOrder()
            {
                if (Session["user_store"] != null)
                {
                    var user = (int)Session["user_store"];

                    var orders = (from user_1 in userContext.Get()
                                  join order_data in ordersContext.Get() on user_1.Users_ID equals order_data.User_ids
                                  join track in trackingContext.Get() on order_data.Order_ID equals track.Order_ID
                                  select track).ToList();
                    return View(orders);
                }
                return RedirectToAction("Login", "User");
            }
            public ActionResult ShowUnPaidOrder()
            {
                if (Session["user_store"] != null)
                {
                    var user = (int)Session["user_store"];
                    var orders = (from users in userContext.Get()
                                  join order_data in ordersContext.Get() on users.Users_ID equals order_data.User_ids
                                  join pay in paymentContext.Get() on order_data.Order_ID equals pay.Order_ID
                                  where pay.Pay_Status == false
                                  select pay
                                 ).ToList();

                    return View(orders);
                }
                return RedirectToAction("Login", "User");
            }


        }
    
}

Project/Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["email"] != null)
                    {
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                        @*<li>@Html.ActionLink("User SignUp", "SignUp", "User")</li>*@
                        <li>@Html.ActionLink("LOGOUT", "LogOut", "User")</li>
                        if ((int)Session["Role"] == 12)
                        {
                            //    <li>@Html.ActionLink("PlaceOrder", "PlaceOrder", "Order")</li>
                            <li>@Html.ActionLink("PLACED ORDERS", "ShowPlacedOrder", "Orders")</li>
                            <li>@Html.ActionLink("PENDING ORDERS", "ShowUnPaidOrder", "Orders")</li>
                            <li>@Html.ActionLink("NEW ORDER", "PlaceOrder", "Orders")</li>
                        }
                        else if ((int)Session["Role"] == 13)
                        {
                            <li>@Html.ActionLink("ORDERS", "DisplayCompany_Orders", "Company")</li>
                            <li>@Html.ActionLink("NEW ROUTE ", "Add_Route", "Shipment")</li>
                            <li>@Html.ActionLink("PENDING ORDERS", "TrackingStatusUpdate", "Tracking")</li>
                            <li>@Html.ActionLink("ROUTES", "ShowAllRoutes", "Company")</li>
                        }
                        else
                        {

                            <li>@Html.ActionLink("APPROVE", "Request_List", "Admin")</li>
                            <li>@Html.ActionLink("SEARCH", "Search", "Company")</li>
                            <li>@Html.ActionLink("USERS", "Users", "Admin")</li>
                            <li>@Html.ActionLink("ORDERS", "ShowOrders", "Admin")</li>
                            <li>@Html.ActionLink("COMPANY", "Companies", "Admin")</li>
                        }
                    }
                    else
                    {
                        <li>@Html.ActionLink("LOGIN", "Login", "User")</li>
                        <li>@Html.ActionLink("TRACK ORDER", "Search", "Company")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>