Project/Project/Models/Tracking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Tracking
    {
        public Nullable<int> Order_ID { get; set; }
        public int Tracking_Number { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public string Order_Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Order_Details Order_Details { get; set; }
    }
}

Project/Project/Controllers/TrackingController.cs
using Project.Models;
using Project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class TrackingController : Controller
    {
        // GET: Tracking
        TrackingContext trackingContext;
        UserContext userContext;
        CompanyContext companyContext;
        public TrackingController()
        {
            trackingContext = new TrackingContext();
            userContext = new UserContext();
            companyContext = new CompanyContext();
        }

        public ActionResult Add()
        {
            Tracking tracking = new Tracking();
            var l1 = (List<int>)TempData["track_data"];
            TempData.Keep("track_data");
            tracking.Order_ID = l1.ElementAt(0);
            tracking.Company_ID = l1.ElementAt(1);
            tracking.Order_Status = "Order in Process";
            trackingContext.add(tracking);
            return RedirectToAction("ShowPlacedOrder", "Orders");
        }

        public ActionResult TrackingStatusUpdate()
        {
            if (Session["user_store"] != null)
            {
                var id = (from user in userContext.Get() join company in companyContext.Get() on user.Users_ID equals company.User_ids where user.Users_ID == (int)Session["user_store"] select company).ToList();
                var tracking = trackingContext.Get().Where(company_id => company_id.Company_ID == id[0].Company_ID && (company_id.Order_Status).Contains("Success") == false).ToList();
                if (tracking.Count() == 0)
                {
                    ViewBag.CompanyOrdermsg = "Great !! NO Pending Orders ";
                    return View();
                }

                return View(tracking);
            }
            return RedirectToAction("Login", "User");
        }

        public ActionResult Tracking_Update(int id)
        {
            TempData["track_value"] = (int)id;
            List<String> l1 = new List<string> { "Order in Process", "Order is Picked", "Order Shipped", "Order out for Delivary", "Order Successfully Delivary" };
            ViewBag.order_stages = l1;
            var tracking_data = trackingContext.Get_by_TrackID((int)id);
            return View(tracking_data);
        }
        [HttpPost]
        public ActionResult Tracking_Update(Tracking track)
        {

            trackingContext.Update_Status((int)TempData["track_value"], track.Order_Status);
            TempData.Keep("track_value");
            return RedirectToAction("TrackingStatusUpdate");
        }


        public ActionResult TrackingStatus(int id)

        {
            var track = trackingContext.Get_by_TrackID((int)id);
            return View(track);
        }
    }
}

Project/Project/Views/Tracking/TrackingStatus.cshtml
@model Project.Models.Tracking

@{
    ViewData["Title"] = "Search";
}

<body style="background-image: url('/Images/pexels-tom-fisk-3057960.jpg'); background-size: cover;">




    <div class="t_1">
        <div class="body_1">
            <div class="container-1">
                <article class="card" style="margin-left:10px">
                    <header class="card-header"> My Orders / Tracking </header>
                    <div class="card-body" style="margin-left:10px">

                        <article class="card">
                            <div class="card-body row" style="margin-left:10px">
                                <div class="col"> <strong>Order Placed Time:</strong> @Html.DisplayFor(model => model.Order_Details.Order_Time)<br> </div>
                                <div class="col"> <strong>Company ID:</strong>  @Html.DisplayFor(model => model.Company.Company_Name), | <i class="fa fa-phone"></i>@Html.DisplayFor(model => model.Company.Contact_Number) <br> </div>
                                <div class="col"> <strong>Status:</strong> <br>@Html.DisplayFor(model => model.Order_Status) </div>
                                <div class="col"> <strong>Tracking #:</strong> <br> @Html.DisplayFor(model => model.Tracking_Number) </div>
                                <div class="col"> <strong>Destination Address #:</strong> <br> @Html.DisplayFor(model => model.Order_Details.Order_Destination) </div>
                            </div>
                        </article>
                        @if (Model.Order_Status == "Order in Process")
                        {<div class="track">
                                <div class="step active"> <span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order in Process</span> </div>
                                <div class="step "> <span class="icon"> <i class="fa fa-user"></i> </span> <span class="text"> Order is Picked</span> </div>
                                <div class="step "> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> "Order out for Delivary" </span> </div>
                                <div class="step"> <span class="icon"> <i class="fa fa-box"></i> </span> <span class="text">"Order Successfully Delivary"</span> </div>
                            </div>
                            <hr>
                            //"Order Shipped", "Order out for Delivary", "Order Successfully Delivary"
                        }
                        else if (Model.Order_Status == "Order is Picked")
                        {
                            <div class="track">
                                <div class="step active"> <span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order in Process</span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-user"></i> </span> <span class="text"> Order is Picked</span> </div>
                                <div class="step "> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Order Shipped </span> </div>
                                <div class="step "> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Order out for Delivary </span> </div>
                                <div class="step"> <span class="icon"> <i class="fa fa-box"></i> </span> <span class="text">Order Successfully Delivary</span> </div>
                            </div>
                            <hr>
                        }
                        else if (Model.Order_Status == "Order Shipped")
                        {
                            <div class="track">
                                <div class="step active"> <span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order in Process</span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-user"></i> </span> <span class="text"> Order is Picked</span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Order Shipped </span> </div>
                                <div class="step "> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Order out for Delivary </span> </div>
                                <div class="step"> <span class="icon"> <i class="fa fa-box"></i> </span> <span class="text">Order Successfully Delivary</span> </div>
                            </div>
                            <hr>
                        }
                        else if (Model.Order_Status == "Order out for Delivary")
                        {
                            <div class="track">
                                <div class="step active"> <span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order in Process</span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-user"></i> </span> <span class="text"> Order is Picked</span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Order Shipped </span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Order out for Delivary </span> </div>
                                <div class="step"> <span class="icon"> <i class="fa fa-box"></i> </span> <span class="text">Order Successfully Delivary</span> </div>
                            </div>
                            <hr>
                        }
                        else if (Model.Order_Status == "Order Successfully Delivary")
                        {
                            <div class="track">
                                <div class="step active"> <span class="icon"> <i class="fa fa-check"></i> </span> <span class="text">Order in Process</span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-user"></i> </span> <span class="text"> Order is Picked</span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Order Shipped </span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-truck"></i> </span> <span class="text"> Order out for Delivary </span> </div>
                                <div class="step active"> <span class="icon"> <i class="fa fa-box"></i> </span> <span class="text">Order Successfully Delivary</span> </div>
                            </div>
                            <hr>
                        }

                    </div>
                </article>
            </div>
        </div>


    </div>
   
      <div style="height:200px;"></div>
    
</body>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/Tracking/TrackingStatusUpdate.cshtml
@model IEnumerable<Project.Models.Tracking>




@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Order_ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tracking_Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company_ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order_Status)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Order_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tracking_Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order_Status)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }
    </table>*@

<style>
    .container-1 {
        display: grid;
        grid-template-columns: 260px 180px 90px 180px;
        grid-template-rows: auto auto auto auto auto auto;
        column-gap: 70px;
        margin-left: 17%;
        margin-right: 14%;
        padding-left: 8%;
        border-block-color: blueviolet;
        background-color: khaki;
    }

    .details {
        grid-column: 1/2;
        grid-row: 1/1;
    }

    .Update {
        grid-column: 2/3;
        grid-row: 1/1;
        margin-top: 25px;
    }

    .select_1 {
        margin-top: 25px;
        grid-column: 3/4;
        grid-row: 1/1;
        margin-right: 15px;
    }
</style>

<body style="background-image: url('/Images/logestic_comp.jpg'); background-size: cover;">

    @if (ViewBag.CompanyOrdermsg != null)
    {
        <div style="text-align:center;background-color:antiquewhite;height:150px;padding-top:10px;margin-top:20px">
            <h2 style="color:cornflowerblue"><b>@ViewBag.CompanyOrdermsg</b></h2>
        </div>
        <div style="height:100px;"></div>
    }
    else
    {
        foreach (var item in Model)
        {
            <div class="container-1">
                <div class="details">

                    <hr />
                    <h5><b>Tracking Number :</b>@Html.DisplayFor(modelItem => item.Tracking_Number)</h5>
                    <h5><b>Order Placed Time :</b>@Html.DisplayFor(modelItem => item.Order_Details.Order_Time)</h5>
                    <h5><b>Destination Status : @Html.DisplayFor(modelItem => item.Order_Details.Dest_Description)</b></h5>
                </div>
                <div class="Update">

                    <br />
                    <h5><b>@Html.DisplayFor(modelItem => item.Order_Status)</b></h5>
                    @*@Html.DropDownListFor(modelItem => item.Order_Status, new SelectList(ViewBag.order_stages), " ---- Update Status ---- ", new { @class = "chzn-select", @style = "width:160px; height:25px;font-size:15px;", @required = "required" })*@
                </div>
                <div class="select_1">
                    <h3>
                        @Html.ActionLink("Update", "Tracking_Update", new { id = (int)item.Tracking_Number }, new { @class = "btn btn-primary" })
                    </h3>
                </div>
            </div>
        }
    }
   
      <div style="height:200px;"></div>
    
</body>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/Project/Views/Tracking/Tracking_Update.cshtml
@model Project.Models.Tracking


<style>
    .container-12 {
        margin-left: 35%;
        margin-top: 50px;
        margin-right: 20%;
        width: 420px;
        background-color: ghostwhite;
        font-family: Courier New, Courier, monospace;
        padding: 20px;
    }
</style>
<body style="background-image: url('/Images/update.jpg'); background-size: cover;">
    @using (Html.BeginForm("Tracking_Update", "Tracking", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="container-12">
            <h3 style="text-align:center;color:cadetblue"><b>UPDATE STATUS</b></h3>
            <hr />
            <h4><b>TRACKING NUMBER :</b> @Html.DisplayFor(model => model.Tracking_Number)</h4>
            <h5><b>ORDER TIMING : @Html.DisplayFor(model => model.Order_Details.Order_Time)</b></h5>
            <br />
            <hr />
            <h4><b>SOURCE : </b>@Html.DisplayFor(model => model.Order_Details.Source_Description)</h4>
            <h4><b>DESTINATION : </b>@Html.DisplayFor(model => model.Order_Details.Dest_Description)</h4>
            <br />
            <span><b>UPDATE STATUS :</b> </span>
            @Html.DropDownListFor(model => model.Order_Status, new SelectList(ViewBag.order_stages), " ----- select status ----- ")
            @Html.ValidationMessageFor(model => model.Order_Status, "", new { @class = "text-danger" })
            <br />
            <div style="margin:20px">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    }

</body>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}